# ci+docxls.yml
# github.com/shenjuexiao
# 20260820

# github.com/xugaoyi/vuepress-theme-vdoing
# github.com/xugaoyi/vuepress-theme-vdoing/blob/master/.github/workflows/ci.yml

# .github/workflows/ci+docxls.yml
name: CI

#on: [push]

# 在 master 分支发生 push 事件时触发
on:
  push:
    branches:
  # 20260820
      # - master
      - main
  workflow_dispatch:

# 20260820
# 赋予写入仓库内容的权限
permissions:
  contents: write
  pages: write
  id-token: write  

# 设置环境变量
env: 
  # 时区（设置时区可使页面中的`最近更新时间`使用该时区时间）
  TZ: Asia/Shanghai

jobs:
  # 自定义名称
  build: 
    # 运行在虚拟机环境ubuntu-latest
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # 20260820
        # node-version: [18.x]
        node-version: [20.x]
        
    steps:
      # 步骤 1
      - name: Checkout 
        # 使用的动作，格式：userName/repoName
        # 作用：检出仓库，获取源码
        # 官方 actions 库：github.com/actions
        # 20260820
        # uses: actions/checkout@v1
        uses: actions/checkout@v4
      # 步骤 2
      - name: Use Node.js ${{ matrix.node-version }}
        # 作用：安装 nodejs
        # 20260820
        # uses: actions/setup-node@v3
        uses: actions/setup-node@v4
        with:
          # 版本
          node-version: ${{ matrix.node-version }}
      # 步骤 3
      - name: Build-and-deploy
        run: |
          remote_addr=`git remote get-url --push origin`
          commit_info=`git describe --all --always --long`
          user_name=`git log -1 --pretty=format:'%an'`
          user_email=`git log -1 --pretty=format:'%ae'`
          deploy_branch=gh-pages
          yarn
          yarn build
          cd docs/.vuepress/dist
          git config --global init.defaultBranch $deploy_branch
          git init
          git config user.name ${user_name}
          git config user.email ${user_email}
          git add -A
          git commit -m "auto deploy, $commit_info"
          remote_addr=`echo $remote_addr | awk -F'://' '{print $2}'`
          remote_addr=https://${user_name}:${{secrets.GITHUB_TOKEN}}@${remote_addr}
          git remote add origin ${remote_addr}
          # 推送到github $deploy_branch分支
          git push origin HEAD:$deploy_branch --force
          